@startuml
hide circle

package "Logic Layer" as Logic {
}

package "Model Layer" as Model {
}

package "UI Layer" as UI {
    interface Ui
    class UiManager
    class MainWindow
    class StatusBarFooter
    class ResultDisplay
    class CommandBox
    class HelpWindow
    class PersonListPanel
    class PersonCard
    abstract class UiPart

    Ui <|-- UiManager
    UiManager --> Logic
    UiManager --> MainWindow
    MainWindow --> Logic
    PersonCard ..> Model

    MainWindow *-- "1" StatusBarFooter
    MainWindow *-- "1" ResultDisplay
    MainWindow *-- "1" CommandBox
    MainWindow *-- "0..1" HelpWindow
    MainWindow *-- "1" PersonListPanel
    PersonListPanel *-- "*" PersonCard

    StatusBarFooter --|> UiPart
    ResultDisplay --|> UiPart
    CommandBox --|> UiPart
    HelpWindow --|> UiPart
    PersonListPanel --|> UiPart
}

@enduml
